name: Build and Test Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: |
        cd backend
        dotnet restore
        
    - name: Build
      run: |
        cd backend
        dotnet build --no-restore --configuration Release
        
    - name: Test
      run: |
        cd backend
        dotnet test --no-build --configuration Release --verbosity normal
        
    - name: Publish
      run: |
        cd backend
        dotnet publish --no-build --configuration Release --output ./publish
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: backend/publish/
        retention-days: 30

  # Optional: Deploy to Railway (requires Railway CLI and tokens)
  deploy-to-railway:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH
        
    - name: Deploy to Railway
      run: |
        cd backend
        railway deploy
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      continue-on-error: true